spring:
  application:
    name: spring-jpa-seek-pagination
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql:///seek_pagination_test"
    username: "postgres"
    password: "password"
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        show_sql: true
        format_sql: true